apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubernetes-backend
  namespace: demo-kubernetes-prod
  labels:
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-kubernetes-backend
  template:
    metadata:
      labels:
        app: demo-kubernetes-backend
        version: v1
    spec:
      containers:
      - name: demo-kubernetes-backend
        image: torrient/demo-kubernetes-backend:prod_v2
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "500m"