apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubernetes-backend
  namespace: demo-kubernetes-prod
  labels:
    app: demo-kubernetes-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-kubernetes-backend
  template:
    metadata:
      labels:
        app: demo-kubernetes-backend
    spec:
      containers:
      - name: demo-kubernetes-backend
        image: torrient/demo-kubernetes-backend:prod_v1