apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubernetes-backend
  labels:
    app: demo-kubernetes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kubernetes-backend
  template:
    metadata:
      labels:
        app: demo-kubernetes-backend
    spec:
      containers:
      - name: demo-kubernetes-backend
        image: torrient/demo-kubernetes-backend:v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000